{{include_text('/home/workspace/adc_architecture_baselines_v1/cimloop_public/workspace/models/workloads/problem_base.yaml')}}
problem:
  <<<: *problem_base
  name: layer2_1_conv2
  instance:
    N: 2
    P: 256
    C: 384
    M: 32
